version: '3'

services:
    bd:
        image: mysql
        volumes:
            - bd_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dockpass

    spring:
         build: .
         depends_on:
             - bd
         ports:
             - 8080:8080
         environment:
             SPRING_DATASOURCE_URL: jdbc:mysql://bd:3306/BD_Games?createDatabaseIfNotExist=true
             SPRING_DATASOURCE_PASSWORD: dockpass

volumes:
    bd_data:
         